baseURL: http://example.org/
languageCode: ja-jp
title: My New Site
theme: hugo-osan-theme
copyright: "&copy; 2022 yourname"
paginate: 10

menu:
  header:
    - name: Archives
      weight: 1
      url: /archives

    - name: Tags
      weight: 2
      url: /tags

    - name: GitHub
      weight: 3
      url: https://github.com/
      params:
        newtab: true

params:
  showsource: true
  contenturl: https://github.com/yourname/site-repo/tree/master/content/
  description: Hello
  favicon: #favicon
  image: #ogp image
  postnav: true

markup:
  highlight:
    guessSyntax: true
    style: monokai #see https://xyproto.github.io/splash/docs/all.html

outputs:
  home: [html, rss, json]